# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_coxa_lf:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_coxa_lm:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_coxa_lr:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_coxa_rf:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_coxa_rm:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_coxa_rr:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_femur_lf:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_femur_lm:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_femur_lr:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_femur_rf:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_femur_rm:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_femur_rr:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_tibia_lf:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_tibia_lm:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_tibia_lr:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_tibia_rf:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_tibia_rm:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  joint_tibia_rr:
    has_velocity_limits: true
    max_velocity: 0.52400000000000002
    has_acceleration_limits: false
    max_acceleration: 0